import pygame
"""
THIS WILL BE USED FOR APPLYING TRANSFORMATIONS TO AN IMAGE
A GOOD FEW EXAMPLES COME FROM THE OLD POKEMON GAMES - STATUS EFFECTS OR MOVES WITH ANIMATIONS WILL USE
THE TRANSFORMATION CLASS
"""